Update Jenkinsfile
Hardcoded to avoid using pipeline.properties given the missing plugin in the Microclimate Jenkins. 
ref: java.lang.NoSuchMethodError: No such DSL method 'readProperties'